[tool.black]
line-length = 88
target_version = ['py27', 'py35', 'py36', 'py37']
include = '\.pyi?$'
exclude = '''

(
  /(
      \.eggs         # exclude a few common directories in the
    | \.git          # root of the project
    | \.hg
    | \.mypy_cache
    | \.tox
    | \.venv
    | _build
    | buck-out
    | build
    | dist
    | submodules
    | packages/javascript
    | packages/python/plotly/plotly/matplotlylib/mplexporter
  )/
  | versioneer.py
)
'''